name: Approved PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Message Notify
        if: ${{  github.event.review.state == 'approved' }}
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "<@&${{ vars.PROGRAMMER_ID }}>\n${{ github.event.review.user.login }} approved [Pull Request](<${{ github.event.pull_request.html_url }}>)(${{ github.event.pull_request.title }})!"
